config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
#  hello/urls.py
from django.urls import path
from . import views

app_name = "website"
urlpatterns = [
    path('home', views.home_page_view, name='home'),
    path('inicio', views.inicio_page_view, name='inicio'),
    path('sobre', views.sobre_page_view, name='sobre'),
    path('layout', views.layout_page_view, name='layout')

]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render

def layout_page_view(request):
	return render(request, 'website/layout.html')

def sobre_page_view(request):
	return render(request, 'website/sobre.html')

def inicio_page_view(request):
	return render(request, 'website/inicio.html')

def home_page_view(request):
	return render(request, 'website/home.html')

website/templates/website/home.html
<!-- home.html -->

{% extends 'website/layout.html' %}

{% block main %}
    <h3>Home</h3>
    <p>Esta é a página da Home</p>
{% endblock %}

website/templates/website/inicio.html
<!-- home.html -->

{% extends 'website/layout.html' %}

{% block main %}
    <h3>Inicio</h3>
    <p>Esta é a página de Início</p>
    {% load static %}
{% endblock %}

website/templates/website/layout.html
<!-- layout.html -->
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
    		<title>Website</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	</head>
	<body>
	    <header class="jumbotron text-center">
        <h1>WEBSITE</h1>
        <p>A criação de um website😁</p>
        <nav>
        <a href="{% url 'website:home' %}"  type = "button" class="btn btn-info">Home</a>
        <a href="{% url 'website:inicio' %}"  type = "button" class="btn btn-info">Início</a>
        <a href="{% url 'website:sobre' %}"  type = "button" class="btn btn-info">Sobre</a>
        </nav>
        </header>
        <footer>Feito por: Ricardo Lourenço</footer>
        <article class="container">
        <main class="col-sm-6">
	    {% block main %}
	    {% endblock main %}
            <!-- layout.html -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
        </main>
        <aside class="col-sm-6">
        <img src="{% static 'website/images/fizz.png' %}">
        </aside>
        </article>
	</body>
</html>

website/templates/website/sobre.html
<!-- home.html -->

{% extends 'website/layout.html' %}

{% block main %}
    <h3>Sobre</h3>
    <p>Laboratório da cadeira de Teoria da computação</p>
{% endblock %}